# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blogger_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='blogger',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='posted_blog',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog', to_field='title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='posted_by',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blogger', to_field='username'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='blogs',
            field=models.ManyToManyField(through='blogapp.BlogPost', to='blogapp.Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ManyToManyField(through='blogapp.BlogPost', to='blogapp.Blogger'),
        ),
    ]
