# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
