# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20171011_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='posted_blog',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='posted_by',
        ),
        migrations.RenameField(
            model_name='blogger',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blogger'),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
