# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20171011_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
