# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blog_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
