# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_blogger_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='user',
            new_name='username',
        ),
    ]
