# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20171012_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogger',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blogger',
            name='blogs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog'),
        ),
    ]
