# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20171017_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blogger',
            name='blogs',
            field=models.ManyToManyField(default='', to='blogapp.Blog'),
        ),
    ]
