# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20171017_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='blogs',
            field=models.ManyToManyField(to='blogapp.Blog'),
        ),
    ]
