# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20171017_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='blogger',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='blogs',
        ),
    ]
