# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20171017_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ManyToManyField(default='', to='blogapp.Blogger'),
        ),
    ]
