# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_auto_20171017_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
