# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_remove_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blogger'),
        ),
    ]
