# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20171017_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.CharField(choices=[('shoaib', 'shoaib '), ('hammad', 'hammad '), ('Abdur', 'Abdur Rahman')], max_length=100),
        ),
    ]
