# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0002_auto_20170815_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='homeservice.Customer', to_field='username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_service',
            field=models.ForeignKey(db_column='service_type', on_delete=django.db.models.deletion.CASCADE, to='homeservice.Service', to_field='service_type'),
        ),
    ]
