# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0006_auto_20170815_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=models.CharField(default='', max_length=100, unique=True), max_length=100),
        ),
    ]
