# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField()),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservice.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Car Wash', 'Car Wash'), ('Laundry', 'Laundry'), ('Grocery', 'Grocery'), ('Cooking', 'Cook Food')], default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservice.Service'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(through='homeservice.Order', to='homeservice.Service'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
