# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0004_auto_20170815_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
