# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservice.Customer', to_field='username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservice.Service', to_field='service_type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Car Wash', 'Car Wash'), ('Laundry', 'Laundry'), ('Grocery', 'Grocery'), ('Cooking', 'Cook Food')], default='', max_length=100, unique=True),
        ),
    ]
