# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice', '0003_auto_20170815_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_status',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.CASCADE, to='homeservice.ServiceStatus', to_field='status'),
        ),
    ]
